services:
  - type: web
    name: listingtree-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: your_mongodb_connection_string_here
      - key: JWT_SECRET
        generateValue: true
