services:
  - type: web
    name: servicehub
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: your_mongodb_connection_string_here
      - key: JWT_SECRET
        generateValue: true
