# render.yaml
services:
  - type: web
    name: servicehub-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: servicehub-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
